// GOOGLE O AUTH

// FILTER USERS BY SOCIETY ID COLLECTED FROM THE ADMIN SESSION DATA

// FILTER MEETINGS BY SOCIETY ID COLLECTED FROM THE ADMIN SESSION DATA

// ADD MEETING BY SOCIETY ID COLLECTED FROM THE ADMIN SESSION DATA

// SORT MEETINGS BY DATES

// FILTER CIRCULARS BY SOCIETY ID COLLECTED FROM THE ADMIN SESSION DATA

// SORT CIRCULARS BY DATE

// PASS A USER OBJECT CONTAINING USERID, NAME AND BLOCKNO IN COMPLAINT MODEL

// DELETE THE COMPLAINT FROM THE USER PAGE
